# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='helloworld.proto',
  package='helloworld',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10helloworld.proto\x12\nhelloworld\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\xb5\x01\n\x12GetDeptUserRequest\x12\x0f\n\x07\x64\x65pt_id\x18\x01 \x01(\r\x12\x11\n\tdept_name\x18\x02 \x01(\t\x12\x10\n\x08uid_list\x18\x03 \x03(\r\x12:\n\x06\x66ilter\x18\x04 \x03(\x0b\x32*.helloworld.GetDeptUserRequest.FilterEntry\x1a-\n\x0b\x46ilterEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xc6\x01\n\x13GetDeptUserResponse\x12(\n\tuser_list\x18\x01 \x03(\x0b\x32\x15.helloworld.BasicUser\x12>\n\x08user_map\x18\x02 \x03(\x0b\x32,.helloworld.GetDeptUserResponse.UserMapEntry\x1a\x45\n\x0cUserMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.helloworld.BasicUser:\x02\x38\x01\"%\n\tBasicUser\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\"%\n\x11UploadUserRequest\x12\x10\n\x08info_zip\x18\x01 \x01(\x0c\"=\n\x12UploadUserResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x32\xed\x01\n\x07Greeter\x12\x41\n\x08SayHello\x12\x18.helloworld.HelloRequest\x1a\x19.helloworld.HelloResponse\"\x00\x12P\n\x0bGetDeptUser\x12\x1e.helloworld.GetDeptUserRequest\x1a\x1f.helloworld.GetDeptUserResponse\"\x00\x12M\n\nUploadUser\x12\x1d.helloworld.UploadUserRequest\x1a\x1e.helloworld.UploadUserResponse\"\x00\x62\x06proto3'
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='helloworld.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='helloworld.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=60,
)


_HELLORESPONSE = _descriptor.Descriptor(
  name='HelloResponse',
  full_name='helloworld.HelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.HelloResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=94,
)


_GETDEPTUSERREQUEST_FILTERENTRY = _descriptor.Descriptor(
  name='FilterEntry',
  full_name='helloworld.GetDeptUserRequest.FilterEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='helloworld.GetDeptUserRequest.FilterEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='helloworld.GetDeptUserRequest.FilterEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=278,
)

_GETDEPTUSERREQUEST = _descriptor.Descriptor(
  name='GetDeptUserRequest',
  full_name='helloworld.GetDeptUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dept_id', full_name='helloworld.GetDeptUserRequest.dept_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dept_name', full_name='helloworld.GetDeptUserRequest.dept_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uid_list', full_name='helloworld.GetDeptUserRequest.uid_list', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filter', full_name='helloworld.GetDeptUserRequest.filter', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GETDEPTUSERREQUEST_FILTERENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=278,
)


_GETDEPTUSERRESPONSE_USERMAPENTRY = _descriptor.Descriptor(
  name='UserMapEntry',
  full_name='helloworld.GetDeptUserResponse.UserMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='helloworld.GetDeptUserResponse.UserMapEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='helloworld.GetDeptUserResponse.UserMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=479,
)

_GETDEPTUSERRESPONSE = _descriptor.Descriptor(
  name='GetDeptUserResponse',
  full_name='helloworld.GetDeptUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_list', full_name='helloworld.GetDeptUserResponse.user_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_map', full_name='helloworld.GetDeptUserResponse.user_map', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GETDEPTUSERRESPONSE_USERMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=479,
)


_BASICUSER = _descriptor.Descriptor(
  name='BasicUser',
  full_name='helloworld.BasicUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='helloworld.BasicUser.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='helloworld.BasicUser.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=481,
  serialized_end=518,
)


_UPLOADUSERREQUEST = _descriptor.Descriptor(
  name='UploadUserRequest',
  full_name='helloworld.UploadUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='info_zip', full_name='helloworld.UploadUserRequest.info_zip', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=520,
  serialized_end=557,
)


_UPLOADUSERRESPONSE = _descriptor.Descriptor(
  name='UploadUserResponse',
  full_name='helloworld.UploadUserResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='helloworld.UploadUserResponse.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='helloworld.UploadUserResponse.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='helloworld.UploadUserResponse.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=559,
  serialized_end=620,
)

_GETDEPTUSERREQUEST_FILTERENTRY.containing_type = _GETDEPTUSERREQUEST
_GETDEPTUSERREQUEST.fields_by_name['filter'].message_type = _GETDEPTUSERREQUEST_FILTERENTRY
_GETDEPTUSERRESPONSE_USERMAPENTRY.fields_by_name['value'].message_type = _BASICUSER
_GETDEPTUSERRESPONSE_USERMAPENTRY.containing_type = _GETDEPTUSERRESPONSE
_GETDEPTUSERRESPONSE.fields_by_name['user_list'].message_type = _BASICUSER
_GETDEPTUSERRESPONSE.fields_by_name['user_map'].message_type = _GETDEPTUSERRESPONSE_USERMAPENTRY
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloResponse'] = _HELLORESPONSE
DESCRIPTOR.message_types_by_name['GetDeptUserRequest'] = _GETDEPTUSERREQUEST
DESCRIPTOR.message_types_by_name['GetDeptUserResponse'] = _GETDEPTUSERRESPONSE
DESCRIPTOR.message_types_by_name['BasicUser'] = _BASICUSER
DESCRIPTOR.message_types_by_name['UploadUserRequest'] = _UPLOADUSERREQUEST
DESCRIPTOR.message_types_by_name['UploadUserResponse'] = _UPLOADUSERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloResponse = _reflection.GeneratedProtocolMessageType('HelloResponse', (_message.Message,), {
  'DESCRIPTOR' : _HELLORESPONSE,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HelloResponse)
  })
_sym_db.RegisterMessage(HelloResponse)

GetDeptUserRequest = _reflection.GeneratedProtocolMessageType('GetDeptUserRequest', (_message.Message,), {

  'FilterEntry' : _reflection.GeneratedProtocolMessageType('FilterEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETDEPTUSERREQUEST_FILTERENTRY,
    '__module__' : 'helloworld_pb2'
    # @@protoc_insertion_point(class_scope:helloworld.GetDeptUserRequest.FilterEntry)
    })
  ,
  'DESCRIPTOR' : _GETDEPTUSERREQUEST,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.GetDeptUserRequest)
  })
_sym_db.RegisterMessage(GetDeptUserRequest)
_sym_db.RegisterMessage(GetDeptUserRequest.FilterEntry)

GetDeptUserResponse = _reflection.GeneratedProtocolMessageType('GetDeptUserResponse', (_message.Message,), {

  'UserMapEntry' : _reflection.GeneratedProtocolMessageType('UserMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETDEPTUSERRESPONSE_USERMAPENTRY,
    '__module__' : 'helloworld_pb2'
    # @@protoc_insertion_point(class_scope:helloworld.GetDeptUserResponse.UserMapEntry)
    })
  ,
  'DESCRIPTOR' : _GETDEPTUSERRESPONSE,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.GetDeptUserResponse)
  })
_sym_db.RegisterMessage(GetDeptUserResponse)
_sym_db.RegisterMessage(GetDeptUserResponse.UserMapEntry)

BasicUser = _reflection.GeneratedProtocolMessageType('BasicUser', (_message.Message,), {
  'DESCRIPTOR' : _BASICUSER,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.BasicUser)
  })
_sym_db.RegisterMessage(BasicUser)

UploadUserRequest = _reflection.GeneratedProtocolMessageType('UploadUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADUSERREQUEST,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.UploadUserRequest)
  })
_sym_db.RegisterMessage(UploadUserRequest)

UploadUserResponse = _reflection.GeneratedProtocolMessageType('UploadUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADUSERRESPONSE,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.UploadUserResponse)
  })
_sym_db.RegisterMessage(UploadUserResponse)


_GETDEPTUSERREQUEST_FILTERENTRY._options = None
_GETDEPTUSERRESPONSE_USERMAPENTRY._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='helloworld.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=623,
  serialized_end=860,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='helloworld.Greeter.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetDeptUser',
    full_name='helloworld.Greeter.GetDeptUser',
    index=1,
    containing_service=None,
    input_type=_GETDEPTUSERREQUEST,
    output_type=_GETDEPTUSERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UploadUser',
    full_name='helloworld.Greeter.UploadUser',
    index=2,
    containing_service=None,
    input_type=_UPLOADUSERREQUEST,
    output_type=_UPLOADUSERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
